name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.2.1
  flutter_riverpod: ^2.4.10
  form_builder_validators: ^9.1.0
  go_router: ^13.1.0
  riverpod: ^2.5.0
  riverpod_annotation: ^2.3.4
  riverpod_generator: ^2.3.10
  riverpod_lint: ^2.3.8
  searchable_listview: ^2.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  custom_lint: ^0.5.11

flutter:
  uses-material-design: true
